sonar.projectKey=seiunx-dev_cridecoder
sonar.organization=seiunx-dev
sonar.projectVersion=0.3.5
sonar.rust.lcov.reportPaths=target/lcov.info

# This is the name and version displayed in the SonarQube Cloud UI.
# sonar.projectName=cridecoder

# Path is relative to this file. Replace "\\" with "/" on Windows.
# sonar.sources=.

# Encoding of the source code. The default is the system encoding.
# sonar.sourceEncoding=UTF-8
